"""
NIFTY 500 constituent tickers (NSE symbols)
Source: NSE India
"""

NIFTY500 = {
    # ── NIFTY 500 ──────────────────────────────────────────────────────────────
    "360ONE":           "360 ONE WAM LIMITED",
    "3MINDIA":           "3M India Limited",
    "AAVAS":           "Aavas Financiers Limited",
    "ABB":           "ABB India Limited",
    "ABBOTINDIA":           "Abbott India Limited",
    "ABREL":           "Aditya Birla Real Estate Limited",
    "ABSLAMC":           "Aditya Birla Sun Life AMC Limited",
    "ACC":           "ACC Limited",
    "ACCELYA":           "Accelya Solutions India Limited",
    "ACE":           "Action Construction Equipment Limited",
    "ACUTAAS":           "Acutaas Chemicals Limited",
    "ADANIENSOL":           "Adani Energy Solutions Limited",
    "ADANIENT":           "Adani Enterprises Limited",
    "ADANIGREEN":           "Adani Green Energy Limited",
    "ADANIPORTS":           "Adani Ports and Special Economic Zone Limited",
    "ADOR":           "Ador Welding Limited",
    "ADVAIT":           "Advait Energy Transitions Limited",
    "AETHER":           "Aether Industries Limited",
    "AFFLE":           "Affle 3i Limited",
    "AHLUCONT":           "Ahluwalia Contracts (India) Limited",
    "AIAENG":           "AIA Engineering Limited",
    "AJANTPHARM":           "Ajanta Pharma Limited",
    "AKZOINDIA":           "Akzo Nobel India Limited",
    "ALIVUS":           "Alivus Life Sciences Limited",
    "ALKEM":           "Alkem Laboratories Limited",
    "ALKYLAMINE":           "Alkyl Amines Chemicals Limited",
    "ALLDIGI":           "Alldigi Tech Limited",
    "AMBER":           "Amber Enterprises India Limited",
    "AMBIKCO":           "Ambika Cotton Mills Limited",
    "ANANDRATHI":           "Anand Rathi Wealth Limited",
    "ANUP":           "The Anup Engineering Limited",
    "ANURAS":           "Anupam Rasayan India Limited",
    "APARINDS":           "Apar Industries Limited",
    "APLAPOLLO":           "APL Apollo Tubes Limited",
    "APOLLOHOSP":           "Apollo Hospitals Enterprise Limited",
    "APOLSINHOT":           "Apollo Sindoori Hotels Limited",
    "ARMANFIN":           "Arman Financial Services Limited",
    "ASAHIINDIA":           "Asahi India Glass Limited",
    "ASALCBR":           "Associated Alcohols & Breweries Ltd.",
    "ASIANPAINT":           "Asian Paints Limited",
    "ASTRAL":           "Astral Limited",
    "ASTRAMICRO":           "Astra Microwave Products Limited",
    "ASTRAZEN":           "AstraZeneca Pharma India Limited",
    "ATHERENERG":           "Ather Energy Limited",
    "ATLANTAELE":           "Atlanta Electricals Limited",
    "ATUL":           "Atul Limited",
    "AUBANK":           "AU Small Finance Bank Limited",
    "AURIONPRO":           "Aurionpro Solutions Limited",
    "AUROPHARMA":           "Aurobindo Pharma Limited",
    "AUTOAXLES":           "Automotive Axles Limited",
    "AVALON":           "Avalon Technologies Limited",
    "AVANTIFEED":           "Avanti Feeds Limited",
    "AXISBANK":           "Axis Bank Limited",
    "AXISCADES":           "AXISCADES Technologies Limited",
    "AZAD":           "Azad Engineering Limited",
    "BAJAJ-AUTO":           "Bajaj Auto Limited",
    "BAJAJFINSV":           "Bajaj Finserv Limited",
    "BAJAJHLDNG":           "Bajaj Holdings & Investment Limited",
    "BAJFINANCE":           "Bajaj Finance Limited",
    "BALAMINES":           "Balaji Amines Limited",
    "BALKRISIND":           "Balkrishna Industries Limited",
    "BANARISUG":           "Bannari Amman Sugars Limited",
    "BASF":           "BASF India Limited",
    "BAYERCROP":           "Bayer Cropscience Limited",
    "BBL":           "Bharat Bijlee Limited",
    "BBTC":           "The Bombay Burmah Trading Corporation Limited",
    "BDL":           "Bharat Dynamics Limited",
    "BEML":           "BEML Limited",
    "BETA":           "Beta Drugs Limited",
    "BHARATFORG":           "Bharat Forge Limited",
    "BHARATRAS":           "Bharat Rasayan Limited",
    "BHARTIARTL":           "Bharti Airtel Limited",
    "BHARTIHEXA":           "Bharti Hexacom Limited",
    "BIRLACORPN":           "Birla Corporation Limited",
    "BIRLANU":           "BirlaNu Limited",
    "BLUEDART":           "Blue Dart Express Limited",
    "BLUESTARCO":           "Blue Star Limited",
    "BOSCH-HCIL":           "BOSCH HOME COMFORT INDIA LIMITED",
    "BOSCHLTD":           "Bosch Limited",
    "BRITANNIA":           "Britannia Industries Limited",
    "BSE":           "BSE Limited",
    "BUILDPRO":           "Shankara Buildpro Limited",
    "CANFINHOME":           "Can Fin Homes Limited",
    "CAPLIPOINT":           "Caplin Point Laboratories Limited",
    "CARBORUNIV":           "Carborundum Universal Limited",
    "CARERATING":           "CARE Ratings Limited",
    "CARTRADE":           "Cartrade Tech Limited",
    "CARYSIL":           "CARYSIL LIMITED",
    "CCL":           "CCL Products (India) Limited",
    "CDSL":           "Central Depository Services (India) Limited",
    "CEATLTD":           "CEAT Limited",
    "CEINSYS":           "Ceinsys Tech Limited",
    "CENTUM":           "Centum Electronics Limited",
    "CERA":           "Cera Sanitaryware Limited",
    "CHALET":           "Chalet Hotels Limited",
    "CHENNPETRO":           "Chennai Petroleum Corporation Limited",
    "CHEVIOT":           "Cheviot Company Limited",
    "CHOLAFIN":           "Cholamandalam Investment and Finance Company Limited",
    "CHOLAHLDNG":           "Cholamandalam Financial Holdings Limited",
    "CIGNITITEC":           "Cigniti Technologies Limited",
    "CIPLA":           "Cipla Limited",
    "CLEANMAX":           "Clean Max Enviro Energy Solutions Limited",
    "COCHINSHIP":           "Cochin Shipyard Limited",
    "COFORGE":           "Coforge Limited",
    "COLPAL":           "Colgate Palmolive (India) Limited",
    "CONCORDBIO":           "Concord Biotech Limited",
    "COROMANDEL":           "Coromandel International Limited",
    "CORONA":           "CORONA Remedies Limited",
    "CPPLUS":           "Aditya Infotech Limited",
    "CRAFTSMAN":           "Craftsman Automation Limited",
    "CREDITACC":           "CREDITACCESS GRAMEEN LIMITED",
    "CRISIL":           "CRISIL Limited",
    "CUMMINSIND":           "Cummins India Limited",
    "CYIENT":           "Cyient Limited",
    "DALBHARAT":           "Dalmia Bharat Limited",
    "DATAPATTNS":           "Data Patterns (India) Limited",
    "DCMSHRIRAM":           "DCM Shriram Limited",
    "DEEPAKFERT":           "Deepak Fertilizers and Petrochemicals Corporation Limited",
    "DEEPAKNTR":           "Deepak Nitrite Limited",
    "DENORA":           "De Nora India Limited",
    "DHANUKA":           "Dhanuka Agritech Limited",
    "DHUNINV":           "Dhunseri Investments Limited",
    "DIAMONDYD":           "Prataap Snacks Limited",
    "DIVISLAB":           "Divi's Laboratories Limited",
    "DIXON":           "Dixon Technologies (India) Limited",
    "DMART":           "Avenue Supermarts Limited",
    "DODLA":           "Dodla Dairy Limited",
    "DOMS":           "DOMS Industries Limited",
    "DPABHUSHAN":           "D. P. Abhushan Limited",
    "DREDGECORP":           "Dredging Corporation of India Limited",
    "DRREDDY":           "Dr. Reddy's Laboratories Limited",
    "DSSL":           "Dynacons Systems & Solutions Limited",
    "DYNAMATECH":           "Dynamatic Technologies Limited",
    "E2E":           "E2E Networks Limited",
    "ECLERX":           "eClerx Services Limited",
    "EICHERMOT":           "Eicher Motors Limited",
    "EIDPARRY":           "EID Parry India Limited",
    "EIMCOELECO":           "Eimco Elecon (India) Limited",
    "ELDEHSG":           "Eldeco Housing And Industries Limited",
    "EMCURE":           "Emcure Pharmaceuticals Limited",
    "ENDURANCE":           "Endurance Technologies Limited",
    "ENRIN":           "Siemens Energy India Limited",
    "ENTERO":           "Entero Healthcare Solutions Limited",
    "EPIGRAL":           "Epigral Limited",
    "ERIS":           "Eris Lifesciences Limited",
    "ESABINDIA":           "Esab India Limited",
    "ESCORTS":           "Escorts Kubota Limited",
    "ETHOSLTD":           "Ethos Limited",
    "EXCELINDUS":           "Excel Industries Limited",
    "EXPLEOSOL":           "Expleo Solutions Limited",
    "FACT":           "Fertilizers and Chemicals Travancore Limited",
    "FIEMIND":           "Fiem Industries Limited",
    "FINCABLES":           "Finolex Cables Limited",
    "FINEORG":           "Fine Organic Industries Limited",
    "FLUOROCHEM":           "Gujarat Fluorochemicals Limited",
    "FORCEMOT":           "FORCE MOTORS LTD",
    "FORTIS":           "Fortis Healthcare Limited",
    "FOSECOIND":           "Foseco India Limited",
    "FRACTAL":           "Fractal Analytics Limited",
    "GABRIEL":           "Gabriel India Limited",
    "GALAXYSURF":           "Galaxy Surfactants Limited",
    "GANDHITUBE":           "Gandhi Special Tubes Limited",
    "GANECOS":           "Ganesha Ecosphere Limited",
    "GESHIP":           "The Great Eastern Shipping Company Limited",
    "GILLETTE":           "Gillette India Limited",
    "GKWLIMITED":           "GKW Limited",
    "GLAND":           "Gland Pharma Limited",
    "GLAXO":           "GlaxoSmithKline Pharmaceuticals Limited",
    "GLENMARK":           "Glenmark Pharmaceuticals Limited",
    "GLOBUSSPR":           "Globus Spirits Limited",
    "GMBREW":           "GM Breweries Limited",
    "GMMPFAUDLR":           "GMM Pfaudler Limited",
    "GODFRYPHLP":           "Godfrey Phillips India Limited",
    "GODREJCP":           "Godrej Consumer Products Limited",
    "GODREJIND":           "Godrej Industries Limited",
    "GODREJPROP":           "Godrej Properties Limited",
    "GOODLUCK":           "Goodluck India Limited",
    "GRASIM":           "Grasim Industries Limited",
    "GRAVITA":           "Gravita India Limited",
    "GRINDWELL":           "Grindwell Norton Limited",
    "GRINFRA":           "G R Infraprojects Limited",
    "GROBTEA":           "The Grob Tea Company Limited",
    "GRPLTD":           "GRP Limited",
    "GRSE":           "Garden Reach Shipbuilders & Engineers Limited",
    "GRWRHITECH":           "Garware Hi-Tech Films Limited",
    "GULFOILLUB":           "Gulf Oil Lubricants India Limited",
    "GVT&D":           "GE Vernova T&D India Limited",
    "HAL":           "Hindustan Aeronautics Limited",
    "HALEOSLABS":           "HALEOS LABS LIMITED",
    "HAPPYFORGE":           "Happy Forgings Limited",
    "HATSUN":           "Hatsun Agro Product Limited",
    "HAVELLS":           "Havells India Limited",
    "HCLTECH":           "HCL Technologies Limited",
    "HDFCAMC":           "HDFC Asset Management Company Limited",
    "HDFCBANK":           "HDFC Bank Limited",
    "HEROMOTOCO":           "Hero MotoCorp Limited",
    "HESTERBIO":           "Hester Biosciences Limited",
    "HINDALCO":           "Hindalco Industries Limited",
    "HINDUNILVR":           "Hindustan Unilever Limited",
    "HIRECT":           "Hind Rectifiers Limited",
    "HOMEFIRST":           "Home First Finance Company India Limited",
    "HONAUT":           "Honeywell Automation India Limited",
    "HONDAPOWER":           "Honda India Power Products Limited",
    "HYUNDAI":           "Hyundai Motor India Limited",
    "ICEMAKE":           "Ice Make Refrigeration Limited",
    "ICICIAMC":           "ICICI Prudential Asset Management Company Limited",
    "ICICIBANK":           "ICICI Bank Limited",
    "ICICIGI":           "ICICI Lombard General Insurance Company Limited",
    "ICRA":           "ICRA Limited",
    "IFBAGRO":           "IFB Agro Industries Limited",
    "IFBIND":           "IFB Industries Limited",
    "IKS":           "Inventurus Knowledge Solutions Limited",
    "IMFA":           "Indian Metals & Ferro Alloys Limited",
    "IMPAL":           "India Motor Parts and Accessories Limited",
    "INDIAGLYCO":           "India Glycols Limited",
    "INDIAMART":           "Indiamart Intermesh Limited",
    "INDIANB":           "Indian Bank",
    "INDIASHLTR":           "India Shelter Finance Corporation Limited",
    "INDIGO":           "InterGlobe Aviation Limited",
    "INDIGOPNTS":           "Indigo Paints Limited",
    "INDNIPPON":           "India Nippon Electricals Limited",
    "INDOTECH":           "Indo Tech Transformers Limited",
    "INDUSINDBK":           "IndusInd Bank Limited",
    "INFY":           "Infosys Limited",
    "INGERRAND":           "Ingersoll Rand (India) Limited",
    "INOXINDIA":           "INOX India Limited",
    "INTERARCH":           "Interarch Building Solutions Limited",
    "IPCALAB":           "IPCA Laboratories Limited",
    "ISGEC":           "Isgec Heavy Engineering Limited",
    "JBCHEPHARM":           "JB Chemicals & Pharmaceuticals Limited",
    "JINDALPHOT":           "Jindal Photo Limited",
    "JINDALPOLY":           "Jindal Poly Films Limited",
    "JINDALSTEL":           "JINDAL STEEL LIMITED",
    "JKCEMENT":           "JK Cement Limited",
    "JLHL":           "Jupiter Life Line Hospitals Limited",
    "JPOLYINVST":           "Jindal Poly Investment and Finance Company Limited",
    "JSL":           "Jindal Stainless Limited",
    "JSWHL":           "JSW Holdings Limited",
    "JSWSTEEL":           "JSW Steel Limited",
    "JUBLCPL":           "Jubilant Agri and Consumer Products Limited",
    "JUBLPHARMA":           "Jubilant Pharmova Limited",
    "JYOTICNC":           "Jyoti CNC Automation Limited",
    "KAJARIACER":           "Kajaria Ceramics Limited",
    "KAUSHALYA":           "Kaushalya Infrastructure Development Corporation Limited",
    "KAYNES":           "Kaynes Technology India Limited",
    "KDDL":           "KDDL Limited",
    "KEI":           "KEI Industries Limited",
    "KERNEX":           "Kernex Microsystems (India) Limited",
    "KFINTECH":           "Kfin Technologies Limited",
    "KICL":           "Kalyani Investment Company Limited",
    "KINGFA":           "Kingfa Science & Technology (India) Limited",
    "KIRLOSBROS":           "Kirloskar Brothers Limited",
    "KIRLOSENG":           "Kirloskar Oil Engines Limited",
    "KIRLOSIND":           "Kirloskar Industries Limited",
    "KIRLPNU":           "Kirloskar Pneumatic Company Limited",
    "KMEW":           "Knowledge Marine & Engineering Works Limited",
    "KPIL":           "Kalpataru Projects International Limited",
    "KPRMILL":           "K.P.R. Mill Limited",
    "KRISHNADEF":           "Krishna Defence And Allied Industries Limited",
    "KRN":           "KRN Heat Exchanger and Refrigeration Limited",
    "KSB":           "Ksb Limited",
    "KSCL":           "Kaveri Seed Company Limited",
    "LALPATHLAB":           "Dr. Lal Path Labs Ltd.",
    "LAURUSLABS":           "Laurus Labs Limited",
    "LGBBROSLTD":           "LG Balakrishnan & Bros Limited",
    "LGEINDIA":           "LG Electronics India Limited",
    "LICI":           "Life Insurance Corporation Of India",
    "LINDEINDIA":           "Linde India Limited",
    "LLOYDSME":           "Lloyds Metals And Energy Limited",
    "LMW":           "LMW Limited",
    "LODHA":           "Lodha Developers Limited",
    "LT":           "Larsen & Toubro Limited",
    "LTM":           "LTIMindtree Limited",
    "LTTS":           "L&T Technology Services Limited",
    "LUMAXIND":           "Lumax Industries Limited",
    "LUMAXTECH":           "Lumax Auto Technologies Limited",
    "LUPIN":           "Lupin Limited",
    "LUXIND":           "Lux Industries Limited",
    "M&M":           "Mahindra & Mahindra Limited",
    "MACPOWER":           "Macpower CNC Machines Limited",
    "MAHASTEEL":           "Mahamaya Steel Industries Limited",
    "MAHSCOOTER":           "Maharashtra Scooters Limited",
    "MAITHANALL":           "Maithan Alloys Limited",
    "MALLCOM":           "Mallcom (India) Limited",
    "MANGLMCEM":           "Mangalam Cement Limited",
    "MANKIND":           "Mankind Pharma Limited",
    "MANORAMA":           "Manorama Industries Limited",
    "MAPMYINDIA":           "C.E. Info Systems Limited",
    "MARICO":           "Marico Limited",
    "MARUTI":           "Maruti Suzuki India Limited",
    "MASTEK":           "Mastek Limited",
    "MAXHEALTH":           "Max Healthcare Institute Limited",
    "MAZDOCK":           "Mazagon Dock Shipbuilders Limited",
    "MCX":           "Multi Commodity Exchange of India Limited",
    "MEDANTA":           "Global Health Limited",
    "MEDPLUS":           "Medplus Health Services Limited",
    "METROBRAND":           "Metro Brands Limited",
    "MFSL":           "Max Financial Services Limited",
    "MGL":           "Mahanagar Gas Limited",
    "MIDWESTLTD":           "Midwest Limited",
    "MOTILALOFS":           "Motilal Oswal Financial Services Limited",
    "MPHASIS":           "MphasiS Limited",
    "MPSLTD":           "MPS Limited",
    "MRF":           "MRF Limited",
    "MTARTECH":           "Mtar Technologies Limited",
    "MUTHOOTFIN":           "Muthoot Finance Limited",
    "NAM-INDIA":           "Nippon Life India Asset Management Limited",
    "NATCOPHARM":           "Natco Pharma Limited",
    "NAUKRI":           "Info Edge (India) Limited",
    "NAVINFLUOR":           "Navin Fluorine International Limited",
    "NBIFIN":           "N. B. I. Industrial Finance Company Limited",
    "NDGL":           "Naga Dhunseri Group Limited",
    "NEOGEN":           "Neogen Chemicals Limited",
    "NESCO":           "Nesco Limited",
    "NESTLEIND":           "Nestle India Limited",
    "NETWEB":           "Netweb Technologies India Limited",
    "NEULANDLAB":           "Neuland Laboratories Limited",
    "NGLFINE":           "NGL Fine-Chem Limited",
    "NH":           "Narayana Hrudayalaya Ltd.",
    "NIBE":           "NIBE Limited",
    "NILKAMAL":           "Nilkamal Limited",
    "NPST":           "Network People Services Technologies Limited",
    "NSIL":           "Nalwa Sons Investments Limited",
    "NUCLEUS":           "Nucleus Software Exports Limited",
    "NUVAMA":           "Nuvama Wealth Management Limited",
    "OBEROIRLTY":           "Oberoi Realty Limited",
    "OFSS":           "Oracle Financial Services Software Limited",
    "OLECTRA":           "Olectra Greentech Limited",
    "ONESOURCE":           "Onesource Specialty Pharma Limited",
    "ORISSAMINE":           "The Orissa Minerals Development Company Limited",
    "PAGEIND":           "Page Industries Limited",
    "PASHUPATI":           "Pashupati Cotspin Limited",
    "PAYTM":           "One 97 Communications Limited",
    "PERSISTENT":           "Persistent Systems Limited",
    "PFIZER":           "Pfizer Limited",
    "PGHH":           "Procter & Gamble Hygiene and Health Care Limited",
    "PGHL":           "Procter & Gamble Health Limited",
    "PGIL":           "Pearl Global Industries Limited",
    "PHOENIXLTD":           "The Phoenix Mills Limited",
    "PIDILITIND":           "Pidilite Industries Limited",
    "PIIND":           "PI Industries Limited",
    "PILANIINVS":           "Pilani Investment and Industries Corporation Limited",
    "PIRAMALFIN":           "Piramal Finance Limited",
    "PITTIENG":           "Pitti Engineering Limited",
    "PIXTRANS":           "Pix Transmissions Limited",
    "PKTEA":           "The Peria Karamalai Tea & Produce Company Limited",
    "PNBHOUSING":           "PNB Housing Finance Limited",
    "POCL":           "Pondy Oxides & Chemicals Limited",
    "POKARNA":           "Pokarna Limited",
    "POLICYBZR":           "PB Fintech Limited",
    "POLYCAB":           "Polycab India Limited",
    "POLYMED":           "Poly Medicure Limited",
    "POLYPLEX":           "Polyplex Corporation Limited",
    "POWERINDIA":           "Hitachi Energy India Limited",
    "POWERMECH":           "Power Mech Projects Limited",
    "PREMIERENE":           "Premier Energies Limited",
    "PRESTIGE":           "Prestige Estates Projects Limited",
    "PRIVISCL":           "Privi Speciality Chemicals Limited",
    "PRUDENT":           "Prudent Corporate Advisory Services Limited",
    "PTCIL":           "PTC Industries Limited",
    "PUNJABCHEM":           "Punjab Chemicals & Crop Protection Limited",
    "PVRINOX":           "PVR INOX Limited",
    "QPOWER":           "Quality Power Electrical Equipments Limited",
    "RACLGEAR":           "RACL Geartech Limited",
    "RADICO":           "Radico Khaitan Limited",
    "RAINBOW":           "Rainbow Childrens Medicare Limited",
    "RAMCOCEM":           "The Ramco Cements Limited",
    "RANEHOLDIN":           "Rane Holdings Limited",
    "RATNAMANI":           "Ratnamani Metals & Tubes Limited",
    "RAYMONDLSL":           "Raymond Lifestyle Limited",
    "RELIANCE":           "Reliance Industries Limited",
    "ROSSTECH":           "Rossell Techsys Limited",
    "RPGLIFE":           "RPG Life Sciences Limited",
    "RPSGVENT":           "RPSG VENTURES LIMITED",
    "RRKABEL":           "R R Kabel Limited",
    "RUBICON":           "Rubicon Research Limited",
    "SAFARI":           "Safari Industries (India) Limited",
    "SAILIFE":           "Sai Life Sciences Limited",
    "SANDESH":           "The Sandesh Limited",
    "SANOFI":           "Sanofi India Limited",
    "SANOFICONR":           "Sanofi Consumer Healthcare India Limited",
    "SANSERA":           "Sansera Engineering Limited",
    "SASKEN":           "Sasken Technologies Limited",
    "SBILIFE":           "SBI Life Insurance Company Limited",
    "SBIN":           "State Bank of India",
    "SCHAEFFLER":           "Schaeffler India Limited",
    "SCHNEIDER":           "Schneider Electric Infrastructure Limited",
    "SEAMECLTD":           "Seamec Limited",
    "SEDEMAC":           "SEDEMAC Mechatronics Limited",
    "SENORES":           "Senores Pharmaceuticals Limited",
    "SHAILY":           "Shaily Engineering Plastics Limited",
    "SHARDACROP":           "Sharda Cropchem Limited",
    "SHARDAMOTR":           "Sharda Motor Industries Limited",
    "SHILCTECH":           "Shilchar Technologies Limited",
    "SHREECEM":           "SHREE CEMENT LIMITED",
    "SHRIPISTON":           "Shriram Pistons & Rings Limited",
    "SHRIRAMFIN":           "Shriram Finance Limited",
    "SHYAMMETL":           "Shyam Metalics and Energy Limited",
    "SIEMENS":           "Siemens Limited",
    "SIGNATURE":           "Signatureglobal (India) Limited",
    "SJS":           "S.J.S. Enterprises Limited",
    "SKFINDIA":           "SKF India Limited",
    "SKFINDUS":           "SKF India (Industrial) Limited",
    "SMLMAH":           "SML Mahindra Limited",
    "SOBHA":           "Sobha Limited",
    "SOLARINDS":           "Solar Industries India Limited",
    "SOLEX":           "Solex Energy Limited",
    "SPAL":           "S. P. Apparels Limited",
    "SPECTRUM":           "Spectrum Electrical Industries Limited",
    "SRF":           "SRF Limited",
    "STAR":           "Strides Pharma Science Limited",
    "STYLAMIND":           "Stylam Industries Limited",
    "STYRENIX":           "Styrenix Performance Materials Limited",
    "SUDARSCHEM":           "Sudarshan Chemical Industries Limited",
    "SUMMITSEC":           "Summit Securities Limited",
    "SUNCLAY":           "Sundaram Clayton Limited",
    "SUNDARMFIN":           "Sundaram Finance Limited",
    "SUNDRMFAST":           "Sundram Fasteners Limited",
    "SUNPHARMA":           "Sun Pharmaceutical Industries Limited",
    "SUPREMEIND":           "Supreme Industries Limited",
    "SUYOG":           "Suyog Telematics Limited",
    "SWANDEF":           "Swan Defence and Heavy Industries Limited",
    "SWARAJENG":           "Swaraj Engines Limited",
    "SYMPHONY":           "Symphony Limited",
    "SYRMA":           "Syrma SGS Technology Limited",
    "TASTYBITE":           "Tasty Bite Eatables Limited",
    "TATACOMM":           "Tata Communications Limited",
    "TATACONSUM":           "TATA CONSUMER PRODUCTS LIMITED",
    "TATAELXSI":           "Tata Elxsi Limited",
    "TATVA":           "Tatva Chintan Pharma Chem Limited",
    "TBOTEK":           "TBO Tek Limited",
    "TCI":           "Transport Corporation of India Limited",
    "TCPLPACK":           "TCPL Packaging Limited",
    "TCS":           "Tata Consultancy Services Limited",
    "TDPOWERSYS":           "TD Power Systems Limited",
    "TEAMLEASE":           "Teamlease Services Limited",
    "TECHM":           "Tech Mahindra Limited",
    "TECHNOE":           "Techno Electric & Engineering Company Limited",
    "TEGA":           "Tega Industries Limited",
    "THANGAMAYL":           "Thangamayil Jewellery Limited",
    "THEJO":           "Thejo Engineering Limited",
    "THERMAX":           "Thermax Limited",
    "TIIL":           "Technocraft Industries (India) Limited",
    "TIINDIA":           "Tube Investments of India Limited",
    "TIMKEN":           "Timken India Limited",
    "TITAN":           "Titan Company Limited",
    "TORNTPHARM":           "Torrent Pharmaceuticals Limited",
    "TORNTPOWER":           "Torrent Power Limited",
    "TRAVELFOOD":           "Travel Food Services Limited",
    "TRENT":           "Trent Limited",
    "TTKHLTCARE":           "TTK Healthcare Limited",
    "TVSHLTD":           "TVS Holdings Limited",
    "TVSMOTOR":           "TVS Motor Company Limited",
    "TVSSRICHAK":           "TVS Srichakra Limited",
    "UBL":           "United Breweries Limited",
    "ULTRACEMCO":           "UltraTech Cement Limited",
    "UNIMECH":           "Unimech Aerospace and Manufacturing Limited",
    "UNITDSPR":           "United Spirits Limited",
    "UNIVCABLES":           "Universal Cables Limited",
    "UNOMINDA":           "UNO Minda Limited",
    "UTIAMC":           "UTI Asset Management Company Limited",
    "VADILALIND":           "Vadilal Industries Limited",
    "VEEDOL":           "Veedol Corporation Limited",
    "VENKEYS":           "Venky's (India) Limited",
    "VENUSPIPES":           "Venus Pipes & Tubes Limited",
    "VENUSREM":           "Venus Remedies Limited",
    "VHL":           "Vardhman Holdings Limited",
    "VIJAYA":           "Vijaya Diagnostic Centre Limited",
    "VINATIORGA":           "Vinati Organics Limited",
    "VINDHYATEL":           "Vindhya Telelinks Limited",
    "VOLTAMP":           "Voltamp Transformers Limited",
    "VOLTAS":           "Voltas Limited",
    "VSTTILLERS":           "V.S.T Tillers Tractors Limited",
    "WAAREEENER":           "Waaree Energies Limited",
    "WAAREERTL":           "Waaree Renewable Technologies Limited",
    "WABAG":           "VA Tech Wabag Limited",
    "WEALTH":           "Wealth First Portfolio Managers Limited",
    "WELCORP":           "Welspun Corp Limited",
    "WELINV":           "Welspun Investments and Commercials Limited",
    "WENDT":           "Wendt (India) Limited",
    "WHEELS":           "Wheels India Limited",
    "WHIRLPOOL":           "Whirlpool of India Limited",
    "WINDLAS":           "Windlas Biotech Limited",
    "WOCKPHARMA":           "Wockhardt Limited",
    "XPROINDIA":           "Xpro India Limited",
    "YASHO":           "Yasho Industries Limited",
    "YATHARTH":            "Yatharth Hospital & Trauma Care Services Limited",
    "ZENTEC":               "Zen Technologies Limited",
    "ZFCVINDIA":           "ZF Commercial Vehicle Control Systems India Limited",
    "ZOTA":                "Zota Health Care LImited",
    "ZYDUSLIFE":           "Zydus Lifesciences Limited",
}
