"""
NIFTY 500 constituent tickers (NSE symbols)
Source: NSE India — as of April 2025
"""

NIFTY500 = {
    # ── NIFTY 50 ──────────────────────────────────────────────────────────────
    "RELIANCE":    "Reliance Industries",
    "TCS":         "Tata Consultancy Svcs",
    "HDFCBANK":    "HDFC Bank",
    "INFY":        "Infosys",
    "ICICIBANK":   "ICICI Bank",
    "HINDUNILVR":  "Hindustan Unilever",
    "ITC":         "ITC Ltd",
    "SBIN":        "State Bank of India",
    "BHARTIARTL":  "Bharti Airtel",
    "KOTAKBANK":   "Kotak Mahindra Bank",
    "LT":          "Larsen & Toubro",
    "ASIANPAINT":  "Asian Paints",
    "AXISBANK":    "Axis Bank",
    "MARUTI":      "Maruti Suzuki",
    "BAJFINANCE":  "Bajaj Finance",
    "WIPRO":       "Wipro",
    "ONGC":        "ONGC",
    "NTPC":        "NTPC",
    "POWERGRID":   "Power Grid Corp",
    "ULTRACEMCO":  "UltraTech Cement",
    "TITAN":       "Titan Company",
    "SUNPHARMA":   "Sun Pharmaceutical",
    "TECHM":       "Tech Mahindra",
    "HCLTECH":     "HCL Technologies",
    "ADANIENT":    "Adani Enterprises",
    "JSWSTEEL":    "JSW Steel",
    "TATAMOTORS":  "Tata Motors",
    "NESTLEIND":   "Nestlé India",
    "DRREDDY":     "Dr Reddy's Labs",
    "DIVISLAB":    "Divi's Laboratories",
    "CIPLA":       "Cipla",
    "BAJAJFINSV":  "Bajaj Finserv",
    "BRITANNIA":   "Britannia Industries",
    "GRASIM":      "Grasim Industries",
    "TATASTEEL":   "Tata Steel",
    "COALINDIA":   "Coal India",
    "HINDALCO":    "Hindalco Industries",
    "HEROMOTOCO":  "Hero MotoCorp",
    "EICHERMOT":   "Eicher Motors",
    "SHREECEM":    "Shree Cement",
    "APOLLOHOSP":  "Apollo Hospitals",
    "BPCL":        "BPCL",
    "INDUSINDBK":  "IndusInd Bank",
    "M&M":         "Mahindra & Mahindra",
    "TATACONSUM":  "Tata Consumer Products",
    "PIDILITIND":  "Pidilite Industries",
    "HAVELLS":     "Havells India",
    "DABUR":       "Dabur India",
    "SIEMENS":     "Siemens India",
    "ADANIPORTS":  "Adani Ports",
    # ── NIFTY NEXT 50 ─────────────────────────────────────────────────────────
    "BAJAJ-AUTO":  "Bajaj Auto",
    "BANKBARODA":  "Bank of Baroda",
    "BERGEPAINT":  "Berger Paints",
    "BIOCON":      "Biocon",
    "BOSCHLTD":    "Bosch",
    "CHOLAFIN":    "Cholamandalam Finance",
    "COLPAL":      "Colgate-Palmolive",
    "CONCOR":      "Container Corp",
    "CUMMINSIND":  "Cummins India",
    "DLF":         "DLF",
    "GLAND":       "Gland Pharma",
    "GODREJCP":    "Godrej Consumer Products",
    "GODREJPROP":  "Godrej Properties",
    "HAL":         "Hindustan Aeronautics",
    "ICICIPRULI":  "ICICI Prudential Life",
    "INDUSTOWER":  "Indus Towers",
    "IRCTC":       "IRCTC",
    "LTF":         "L&T Finance",
    "LUPIN":       "Lupin",
    "MARICO":      "Marico",
    "MPHASIS":     "Mphasis",
    "NAUKRI":      "Info Edge",
    "NHPC":        "NHPC",
    "NMDC":        "NMDC",
    "OFSS":        "Oracle Financial Services",
    "PAGEIND":     "Page Industries",
    "PETRONET":    "Petronet LNG",
    "PIIND":       "PI Industries",
    "POLYCAB":     "Polycab India",
    "RECLTD":      "REC Ltd",
    "SBICARD":     "SBI Cards",
    "SBILIFE":     "SBI Life Insurance",
    "SRF":         "SRF",
    "TORNTPHARM":  "Torrent Pharmaceuticals",
    "TRENT":       "Trent",
    "UBL":         "United Breweries",
    "VEDL":        "Vedanta",
    "VOLTAS":      "Voltas",
    "ZOMATO":      "Zomato",
    "PAYTM":       "One97 Communications",
    "NYKAA":       "FSN E-Commerce",
    "POLICYBZR":   "PB Fintech",
    "IRFC":        "Indian Railway Finance",
    "BEL":         "Bharat Electronics",
    "LODHA":       "Macrotech Developers",
    "VBL":         "Varun Beverages",
    # ── NIFTY MIDCAP 150 ──────────────────────────────────────────────────────
    "ABCAPITAL":   "Aditya Birla Capital",
    "ABFRL":       "Aditya Birla Fashion",
    "ACC":         "ACC",
    "AIAENG":      "AIA Engineering",
    "ALKEM":       "Alkem Laboratories",
    "AMBUJACEM":   "Ambuja Cements",
    "APLAPOLLO":   "APL Apollo Tubes",
    "ASTRAL":      "Astral",
    "ATUL":        "Atul",
    "AUBANK":      "AU Small Finance Bank",
    "BALKRISIND":  "Balkrishna Industries",
    "BATAINDIA":   "Bata India",
    "BHARATFORG":  "Bharat Forge",
    "BHEL":        "BHEL",
    "CANBK":       "Canara Bank",
    "CANFINHOME":  "Can Fin Homes",
    "CDSL":        "CDSL",
    "COFORGE":     "Coforge",
    "COROMANDEL":  "Coromandel International",
    "CROMPTON":    "Crompton Greaves Consumer",
    "DALBHARAT":   "Dalmia Bharat",
    "DEEPAKNTR":   "Deepak Nitrite",
    "DIXON":       "Dixon Technologies",
    "ELGIEQUIP":   "Elgi Equipments",
    "EMAMILTD":    "Emami",
    "ESCORTS":     "Escorts Kubota",
    "EXIDEIND":    "Exide Industries",
    "FEDERALBNK":  "Federal Bank",
    "FORCEMOT":    "Force Motors",
    "GAIL":        "GAIL India",
    "GLENMARK":    "Glenmark Pharma",
    "GMRINFRA":    "GMR Airports Infra",
    "GNFC":        "GNFC",
    "GRINDWELL":   "Grindwell Norton",
    "HAPPSTMNDS":  "Happiest Minds",
    "HINDPETRO":   "HPCL",
    "HONAUT":      "Honeywell Automation",
    "IDFCFIRSTB":  "IDFC First Bank",
    "IEX":         "Indian Energy Exchange",
    "IPCALAB":     "IPCA Laboratories",
    "JKCEMENT":    "JK Cement",
    "JUBLFOOD":    "Jubilant Foodworks",
    "KAJARIACER":  "Kajaria Ceramics",
    "KANSAINER":   "Kansai Nerolac",
    "KEC":         "KEC International",
    "KPITTECH":    "KPIT Technologies",
    "LALPATHLAB":  "Dr Lal PathLabs",
    "LAURUSLABS":  "Laurus Labs",
    "LICHSGFIN":   "LIC Housing Finance",
    "LINDEINDIA":  "Linde India",
    "LTTS":        "L&T Technology Services",
    "M&MFIN":      "M&M Financial Services",
    "MANAPPURAM":  "Manappuram Finance",
    "MFSL":        "Max Financial Services",
    "MOTILALOFS":  "Motilal Oswal Financial",
    "MRF":         "MRF",
    "MUTHOOTFIN":  "Muthoot Finance",
    "NATCOPHARM":  "Natco Pharma",
    "NAVINFLUOR":  "Navin Fluorine",
    "NBCC":        "NBCC",
    "NLCINDIA":    "NLC India",
    "OBEROIRLTY":  "Oberoi Realty",
    "PERSISTENT":  "Persistent Systems",
    "PFC":         "Power Finance Corp",
    "PHOENIXLTD":  "Phoenix Mills",
    "PNBHOUSING":  "PNB Housing Finance",
    "PRAJIND":     "Praj Industries",
    "PURVA":       "Puravankara",
    "RAYMOND":     "Raymond",
    "RELAXO":      "Relaxo Footwears",
    "RITES":       "RITES",
    "SCHAEFFLER":  "Schaeffler India",
    "SKFINDIA":    "SKF India",
    "SOBHA":       "Sobha",
    "SUPREMEIND":  "Supreme Industries",
    "TANLA":       "Tanla Platforms",
    "TATACHEM":    "Tata Chemicals",
    "TATACOMM":    "Tata Communications",
    "TATAELXSI":   "Tata Elxsi",
    "THERMAX":     "Thermax",
    "TIMKEN":      "Timken India",
    "TORNTPOWER":  "Torrent Power",
    "TVSMOTOR":    "TVS Motor",
    "UPL":         "UPL",
    "VGUARD":      "V-Guard Industries",
    "VINATIORGA":  "Vinati Organics",
    "WOCKPHARMA":  "Wockhardt",
    "ZEEL":        "Zee Entertainment",
    "ZENSARTECH":  "Zensar Technologies",
    # ── NIFTY SMALLCAP 250 (selection) ────────────────────────────────────────
    "AAVAS":       "Aavas Financiers",
    "ABSLAMC":     "Aditya Birla Sun Life AMC",
    "ACCELYA":     "Accelya Solutions",
    "ACE":         "Action Construction Equipment",
    "ACRYSIL":     "Acrysil",
    "ADANIGREEN":  "Adani Green Energy",
    "ADANIPOWER":  "Adani Power",
    "AEGISCHEM":   "Aegis Chemicals",
    "AFFLE":       "Affle India",
    "AJANTPHARM":  "Ajanta Pharma",
    "AKZOINDIA":   "Akzo Nobel India",
    "AMARAJABAT":  "Amara Raja Energy",
    "AMBER":       "Amber Enterprises",
    "ANEKINDS":    "Aneka Industries",
    "ANGELONE":    "Angel One",
    "ANURAS":      "Anupam Rasayan",
    "APOLLOTYRE":  "Apollo Tyres",
    "APTUS":       "Aptus Value Housing",
    "ARVINDFASN":  "Arvind Fashions",
    "ASAHIINDIA":  "Asahi India Glass",
    "ASHOKLEY":    "Ashok Leyland",
    "ASKAUTOLTD":  "ASK Automotive",
    "ASTRAZEN":    "AstraZeneca India",
    "ATGL":        "Adani Total Gas",
    "ATUL":        "Atul",
    "AUROPHARMA":  "Aurobindo Pharma",
    "BAJAJHFL":    "Bajaj Housing Finance",
    "BALRAMCHIN":  "Balrampur Chini Mills",
    "BASF":        "BASF India",
    "BAYERCROP":   "Bayer Cropscience",
    "BBTC":        "Bombay Burmah Trading",
    "BIRLACORPN":  "Birla Corporation",
    "BLUESTARCO":  "Blue Star",
    "BORORENEW":   "Borosil Renewables",
    "BRIGADE":     "Brigade Enterprises",
    "CAMLINFINE":  "Camlin Fine Sciences",
    "CAPACITE":    "Capacite Infraprojects",
    "CARBORUNIV":  "Carborundum Universal",
    "CASTROLIND":  "Castrol India",
    "CEATLTD":     "CEAT",
    "CENTURYPLY":  "Century Plyboards",
    "CENTURYTEX":  "Century Textiles",
    "CERA":        "Cera Sanitaryware",
    "CESC":        "CESC",
    "CGPOWER":     "CG Power & Industrial",
    "CHAMBLFERT":  "Chambal Fertilisers",
    "CHEMPLASTS":  "Chemplast Sanmar",
    "CLEAN":       "Clean Science & Technology",
    "CMSINFO":     "CMS Info Systems",
    "COCHINSHIP":  "Cochin Shipyard",
    "COLLEGEIND":  "College India",
    "CRAFTSMAN":   "Craftsman Automation",
    "CRISIL":      "CRISIL",
    "CSLTD":       "CSL Finance",
    "DATAPATTNS":  "Data Patterns India",
    "DELHIVERY":   "Delhivery",
    "DELTACORP":   "Delta Corp",
    "DHANI":       "Dhani Services",
    "DHANUKA":     "Dhanuka Agritech",
    "DHARAMASHIP": "Dharamsi Morarji Chemical",
    "DMART":       "Avenue Supermarts",
    "EDELWEISS":   "Edelweiss Financial",
    "EIDPARRY":    "EID Parry India",
    "ELECTCAST":   "Electrosteel Castings",
    "ENGINERSIN":  "Engineers India",
    "EPL":         "EPL",
    "EQUITASBNK":  "Equitas Small Finance Bank",
    "ESABINDIA":   "Esab India",
    "ESCONERGO":   "ESCON Infra Realtor",
    "FINEORG":     "Fine Organic Industries",
    "FINPIPE":     "Finolex Industries",
    "FLUOROCHEM":  "Gujarat Fluorochemicals",
    "FORTIS":      "Fortis Healthcare",
    "FSL":         "Firstsource Solutions",
    "GANDHAR":     "Gandhar Oil Refinery",
    "GARFIBRES":   "Garware Technical Fibres",
    "GESHIP":      "Great Eastern Shipping",
    "GLAND":       "Gland Pharma",
    "GLAXO":       "GSK Pharma India",
    "GLOBE":       "Globe Textiles",
    "GOKEX":       "Gokaldas Exports",
    "GPPL":        "Gujarat Pipavav Port",
    "GRANULES":    "Granules India",
    "GRAPHITE":    "Graphite India",
    "GSFC":        "Gujarat State Fertilizers",
    "GSPL":        "Gujarat State Petronet",
    "HAPPSTMNDS":  "Happiest Minds",
    "HCG":         "Healthcare Global",
    "HFCL":        "HFCL",
    "HIKAL":       "Hikal",
    "HLEGLAS":     "HLE Glascoat",
    "HOMEFIRST":   "Home First Finance",
    "HUDCO":       "HUDCO",
    "IBREALEST":   "Indiabulls Real Estate",
    "IDBI":        "IDBI Bank",
    "IFBIND":      "IFB Industries",
    "IFCI":        "IFCI",
    "IGL":         "Indraprastha Gas",
    "IIFL":        "IIFL Finance",
    "INDIANB":     "Indian Bank",
    "INDIAMART":   "IndiaMART InterMESH",
    "INDIGO":      "InterGlobe Aviation",
    "INDIGOPNTS":  "Indigo Paints",
    "INDOSTAR":    "IndoStar Capital Finance",
    "INGERRAND":   "Ingersoll-Rand India",
    "INTELLECT":   "Intellect Design Arena",
    "IOB":         "Indian Overseas Bank",
    "IOC":         "Indian Oil Corp",
    "ISGEC":       "Isgec Heavy Engineering",
    "ITDC":        "India Tourism Dev Corp",
    "ITI":         "ITI",
    "JASH":        "Jash Engineering",
    "JINDALSAW":   "Jindal SAW",
    "JINDALSTEL":  "Jindal Steel & Power",
    "JKIL":        "J Kumar Infraprojects",
    "JKLAKSHMI":   "JK Lakshmi Cement",
    "JKPAPER":     "JK Paper",
    "JMFINANCIL":  "JM Financial",
    "JPPOWER":     "Jaiprakash Power",
    "JSL":         "Jindal Stainless",
    "JTEKTINDIA":  "JTEKT India",
    "JUBLINGREA":  "Jubilant Ingrevia",
    "JUNIPERHOTL": "Juniper Hotels",
    "JUSTDIAL":    "Just Dial",
    "JYOTHYLAB":   "Jyothy Labs",
    "KALYANKJIL":  "Kalyan Jewellers",
    "KAMAHOLDING": "Kama Holdings",
    "KFINTECH":    "KFin Technologies",
    "KHADIM":      "Khadim India",
    "KHAITANTERM": "Khaitan Terminals",
    "KIRLOSENG":   "Kirloskar Electric",
    "KNRCON":      "KNR Constructions",
    "KOLTEPATIL":  "Kolte-Patil Developers",
    "KRBL":        "KRBL",
    "KSCL":        "Kaveri Seed Company",
    "LATENTVIEW":  "LatentView Analytics",
    "LAXMIMACH":   "Lakshmi Machine Works",
    "LEMONTREE":   "Lemon Tree Hotels",
    "LICI":        "LIC of India",
    "LLOYDSME":    "Lloyd's Metals & Energy",
    "LTIM":        "LTIMindtree",
    "LUXIND":      "Lux Industries",
    "MAHABANK":    "Bank of Maharashtra",
    "MAHSCOOTER":  "Maharashtra Scooters",
    "MAHSEAMLES":  "Maharashtra Seamless",
    "MANKIND":     "Mankind Pharma",
    "MARKSANS":    "Marksans Pharma",
    "MASTEK":      "Mastek",
    "MCDOWELL-N":  "United Spirits",
    "MCX":         "Multi Commodity Exchange",
    "MEDPLUS":     "Medplus Health Services",
    "METROBRAND":  "Metro Brands",
    "MIDHANI":     "Mishra Dhatu Nigam",
    "MINDTREE":    "LTIMindtree",
    "MIRZAINT":    "Mirza International",
    "MMTC":        "MMTC",
    "MOIL":        "MOIL",
    "MOL":         "MOL",
    "MOTHERSON":   "Samvardhana Motherson",
    "MSTCLTD":     "MSTC",
    "MTAR":        "MTAR Technologies",
    "MUKANDLTD":   "Mukand",
    "MULTIBASE":   "Multibase India",
    "NACLIND":     "NACL Industries",
    "NAGAFERT":    "Nagarjuna Fertilizers",
    "NAVA":        "Nava",
    "NESCO":       "Nesco",
    "NETWORK18":   "Network18 Media",
    "NIITLTD":     "NIIT",
    "NITINFIRE":   "Nitin Fire Protection",
    "NLC":         "NLC India",
    "NSLNISP":     "NMDC Steel",
    "NUCLEUS":     "Nucleus Software Exports",
    "NUVAMA":      "Nuvama Wealth Management",
    "OBEROIRLTY":  "Oberoi Realty",
    "OCCL":        "Oriental Carbon & Chem",
    "OIL":         "Oil India",
    "OMAXE":       "Omaxe",
    "OPTIEMUS":    "Optiemus Infracom",
    "ORIENTCEM":   "Orient Cement",
    "ORIENTELEC":  "Orient Electric",
    "ORIENTREF":   "Orient Refractories",
    "PASHUPATI":   "Pashupati Acrylon",
    "PCBL":        "PCBL",
    "PEL":         "Piramal Enterprises",
    "PFIZER":      "Pfizer India",
    "PGIL":        "Pearl Global Industries",
    "PGHH":        "Procter & Gamble Hygiene",
    "PNBGILTS":    "PNB Gilts",
    "PNB":         "Punjab National Bank",
    "PNCINFRA":    "PNC Infratech",
    "POLYMED":     "Poly Medicure",
    "PPLPHARMA":   "Piramal Pharma",
    "PRINCEPIPE":  "Prince Pipes",
    "PRITIKAUTO":  "Pritika Auto Industries",
    "PVRINOX":     "PVR INOX",
    "RADICO":      "Radico Khaitan",
    "RAJESHEXPO":  "Rajesh Exports",
    "RAJRATAN":    "Rajratan Global Wire",
    "RAMCOCEM":    "Ramco Cements",
    "RAMCOSYS":    "Ramco Systems",
    "RBLBANK":     "RBL Bank",
    "RESPONIND":   "Responsive Industries",
    "RKFORGE":     "Ramkrishna Forgings",
    "ROLEXRINGS":  "Rolex Rings",
    "ROUTE":       "Route Mobile",
    "RPGLIFE":     "RPG Life Sciences",
    "RPOWER":      "Reliance Power",
    "RTNPOWER":    "Rattanindia Power",
    "SAFARI":      "Safari Industries",
    "SAIL":        "Steel Authority of India",
    "SAPPHIRE":    "Sapphire Foods",
    "SAREGAMA":    "Saregama India",
    "SBFC":        "SBFC Finance",
    "SEQUENT":     "SeQuent Scientific",
    "SHARDAMOTR":  "Sharda Motor Industries",
    "SHAREINDIA":  "Share India Securities",
    "SHYAMMETL":   "Shyam Metalics & Energy",
    "SJVN":        "SJVN",
    "SKIPPER":     "Skipper",
    "SOLARA":      "Solara Active Pharma",
    "SPARC":       "Sun Pharma Advanced Res",
    "SPTL":        "Sintex Plastics Tech",
    "STARHEALTH":  "Star Health Insurance",
    "STLTECH":     "Sterlite Technologies",
    "SUPPETRO":    "Supreme Petrochem",
    "SURYAROSNI":  "Surya Roshni",
    "SUVEN":       "Suven Life Sciences",
    "SUVENPHAR":   "Suven Pharmaceuticals",
    "SWANENERGY":  "Swan Energy",
    "SYMPHONY":    "Symphony",
    "TARSONS":     "Tarsons Products",
    "TATAINVEST":  "Tata Investment Corp",
    "TATAMETALI":  "Tata Metaliks",
    "TCIEXP":      "TCI Express",
    "TCNSBRANDS":  "TCNS Clothing",
    "TEJASNET":    "Tejas Networks",
    "THYROCARE":   "Thyrocare Technologies",
    "TIINDIA":     "Tube Investments of India",
    "TINPLATE":    "Tinplate Company",
    "TITAGARH":    "Titagarh Rail Systems",
    "TRITURBINE":  "Triveni Turbine",
    "TVSHLTD":     "TVS Holdings",
    "TVSSCS":      "TVS Supply Chain Solutions",
    "UCOBANK":     "UCO Bank",
    "UJJIVANSFB":  "Ujjivan Small Finance Bank",
    "UNIONBANK":   "Union Bank of India",
    "UNOMINDA":    "UNO Minda",
    "USHAMART":    "Usha Martin",
    "UTIAMC":      "UTI Asset Management",
    "VAIBHAVGBL":  "Vaibhav Global",
    "VMART":       "V-Mart Retail",
    "VSTTILLERS":  "VST Tillers Tractors",
    "WABAG":       "VA Tech Wabag",
    "WELCORP":     "Welspun Corp",
    "WELSPUNIND":  "Welspun India",
    "WESTLIFE":    "Westlife Foodworld",
    "WHIRLPOOL":   "Whirlpool of India",
    "WINDLAS":     "Windlas Biotech",
    "WISDOMHSG":   "Wisdom Housing Finance",
    "XCHANGING":   "Xchanging Solutions",
    "YESBANK":     "Yes Bank",
    "ZFCVINDIA":   "ZF Commercial Vehicle",
    "ZIMLAB":      "Zim Laboratories",
    "ZODIACLOTH":  "Zodiac Clothing",
}
